//
// This file was generated by the JavaTM Architecture for 
// XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.08.27 at 05:45:07 PM EDT 
//


package edu.iu.scipolicy.preprocessing.geocoder.coders.yahoo.placefinder.beans;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the edu.iu.scipolicy.preprocessing.geocoder.coders.yahoo.placefinder.beans package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory. It can be used to create new instances 
     * of schema derived classes for package: 
     * edu.iu.scipolicy.preprocessing.geocoder.coders.yahoo.placefinder.beans
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Bounding }.
     * 
     */
    public Bounding createBounding() {
        return new Bounding();
    }

    /**
     * Create an instance of {@link ResultSet }.
     * 
     */
    public ResultSet createResultSet() {
        return new ResultSet();
    }

    /**
     * Create an instance of {@link YahooServiceResult }.
     * 
     */
    public YahooServiceResult createYahooServiceResult() {
        return new YahooServiceResult();
    }

}
