from academic_reference_tests import *
from author_tests import *
from change_password_tests import *
from display_user_profile_tests import *
from edit_profile_tests import *
from forgot_password_tests import *
from logo_tests import *
from log_in_and_out_tests import *
from logged_view_tests import *
from item_description_markup_tests import *
from nav_bar_tests import *
from paginate_tests import *
from postmarkup_tests import *
from profile_datarequests_tests import *
from profile_dataset_tests import *
from profile_general_tests import *
from profile_link_tests import *
from registration_tests import *
from site_index_tests import *
