//
// This file was generated by the JavaTM Architecture for 
// XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.08.27 at 05:45:07 PM EDT 
//


package edu.iu.sci2.preprocessing.geocoder.coders.yahoo.placefinder.beans;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Bounding complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Bounding">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="north" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="south" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="east" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="west" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Bounding", propOrder = {
    "north",
    "south",
    "east",
    "west"
})
public class Bounding {

	private float north;
	private float south;
	private float east;
	private float west;

    /**
     * Gets the value of the north property.
     * 
     */
    public float getNorth() {
        return north;
    }

    /**
     * Sets the value of the north property.
     * 
     */
    public void setNorth(float value) {
        this.north = value;
    }

    /**
     * Gets the value of the south property.
     * 
     */
    public float getSouth() {
        return south;
    }

    /**
     * Sets the value of the south property.
     * 
     */
    public void setSouth(float value) {
        this.south = value;
    }

    /**
     * Gets the value of the east property.
     * 
     */
    public float getEast() {
        return east;
    }

    /**
     * Sets the value of the east property.
     * 
     */
    public void setEast(float value) {
        this.east = value;
    }

    /**
     * Gets the value of the west property.
     * 
     */
    public float getWest() {
        return west;
    }

    /**
     * Sets the value of the west property.
     * 
     */
    public void setWest(float value) {
        this.west = value;
    }

}
