//
// This file was generated by the JavaTM Architecture for 
// XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.08.27 at 05:45:07 PM EDT 
//


package edu.iu.sci2.preprocessing.geocoder.coders.yahoo.placefinder.beans;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for YahooServiceResult complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="YahooServiceResult">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="quality" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="latitude" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="longitude" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="offsetlat" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="offsetlon" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="radius" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="boundingbox" type="{}Bounding" minOccurs="0"/>
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="line1" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="line2" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="line3" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="line4" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="cross" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="house" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="street" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="xstreet" type="{http://www.w3.org/2001/XMLSchema}string" 
 *         																			minOccurs="0"/>
 *         &lt;element name="unittype" type="{http://www.w3.org/2001/XMLSchema}string" 
 *         																			minOccurs="0"/>
 *         &lt;element name="unit" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="postal" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="neighborhood" type="{http://www.w3.org/2001/XMLSchema}string" 
 *         																			minOccurs="0"/>
 *         &lt;element name="city" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="county" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="state" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="country" type="{http://www.w3.org/2001/XMLSchema}string" 
 *         																			minOccurs="0"/>
 *         &lt;element name="level14" type="{http://www.w3.org/2001/XMLSchema}string" 
 *         																			minOccurs="0"/>
 *         &lt;element name="level13" type="{http://www.w3.org/2001/XMLSchema}string" 
 *         																			minOccurs="0"/>
 *         &lt;element name="level12" type="{http://www.w3.org/2001/XMLSchema}string" 
 *         																			minOccurs="0"/>
 *         &lt;element name="level11" type="{http://www.w3.org/2001/XMLSchema}string" 
 *         																			minOccurs="0"/>
 *         &lt;element name="level10" type="{http://www.w3.org/2001/XMLSchema}string" 
 *         																			minOccurs="0"/>
 *         &lt;element name="countrycode" type="{http://www.w3.org/2001/XMLSchema}string" 
 *         																			minOccurs="0"/>
 *         &lt;element name="statecode" type="{http://www.w3.org/2001/XMLSchema}string" 
 *         																			minOccurs="0"/>
 *         &lt;element name="countycode" type="{http://www.w3.org/2001/XMLSchema}string" 
 *         																			minOccurs="0"/>
 *         &lt;element name="level12code" type="{http://www.w3.org/2001/XMLSchema}string" 
 *         																			minOccurs="0"/>
 *         &lt;element name="level11code" type="{http://www.w3.org/2001/XMLSchema}string" 
 *         																			minOccurs="0"/>
 *         &lt;element name="level10code" type="{http://www.w3.org/2001/XMLSchema}string" 
 *         																			minOccurs="0"/>
 *         &lt;element name="areacode" type="{http://www.w3.org/2001/XMLSchema}string" 
 *         																			minOccurs="0"/>
 *         &lt;element name="timezone" type="{http://www.w3.org/2001/XMLSchema}string" 
 *         																			minOccurs="0"/>
 *         &lt;element name="uzip" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="hash" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="woeid" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="woetype" type="{http://www.w3.org/2001/XMLSchema}integer" 
 *         																			minOccurs="0"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "YahooServiceResult", propOrder = {

})
public class YahooServiceResult {

    @XmlElement(required = true)
    private BigInteger quality;
    private float latitude;
    private float longitude;
    private float offsetlat;
    private float offsetlon;
    @XmlElement(required = true)
    private BigInteger radius;
    private Bounding boundingbox;
    private String name;
    private String line1;
    private String line2;
    private String line3;
    private String line4;
    private String cross;
    private String house;
    private String street;
    private String xstreet;
    private String unittype;
    private String unit;
    private String postal;
    private String neighborhood;
    private String city;
    private String county;
    private String state;
    private String country;
    private String level14;
    private String level13;
    private String level12;
    private String level11;
    private String level10;
    private String countrycode;
    private String statecode;
    private String countycode;
    @XmlElement(name = "level12code")
    private String level12Code;
    @XmlElement(name = "level11code")
    private String level11Code;
    @XmlElement(name = "level10code")
    private String level10Code;
    private String areacode;
    private String timezone;
    private String uzip;
    private String hash;
    private BigInteger woeid;
    private BigInteger woetype;

    /**
     * Gets the value of the quality property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getQuality() {
        return quality;
    }

    /**
     * Sets the value of the quality property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setQuality(BigInteger value) {
        this.quality = value;
    }

    /**
     * Gets the value of the latitude property.
     * 
     */
    public float getLatitude() {
        return latitude;
    }

    /**
     * Sets the value of the latitude property.
     * 
     */
    public void setLatitude(float value) {
        this.latitude = value;
    }

    /**
     * Gets the value of the longitude property.
     * 
     */
    public float getLongitude() {
        return longitude;
    }

    /**
     * Sets the value of the longitude property.
     * 
     */
    public void setLongitude(float value) {
        this.longitude = value;
    }

    /**
     * Gets the value of the offsetlat property.
     * 
     */
    public float getOffsetlat() {
        return offsetlat;
    }

    /**
     * Sets the value of the offsetlat property.
     * 
     */
    public void setOffsetlat(float value) {
        this.offsetlat = value;
    }

    /**
     * Gets the value of the offsetlon property.
     * 
     */
    public float getOffsetlon() {
        return offsetlon;
    }

    /**
     * Sets the value of the offsetlon property.
     * 
     */
    public void setOffsetlon(float value) {
        this.offsetlon = value;
    }

    /**
     * Gets the value of the radius property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getRadius() {
        return radius;
    }

    /**
     * Sets the value of the radius property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setRadius(BigInteger value) {
        this.radius = value;
    }

    /**
     * Gets the value of the boundingbox property.
     * 
     * @return
     *     possible object is
     *     {@link Bounding }
     *     
     */
    public Bounding getBoundingbox() {
        return boundingbox;
    }

    /**
     * Sets the value of the boundingbox property.
     * 
     * @param value
     *     allowed object is
     *     {@link Bounding }
     *     
     */
    public void setBoundingbox(Bounding value) {
        this.boundingbox = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the line1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLine1() {
        return line1;
    }

    /**
     * Sets the value of the line1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLine1(String value) {
        this.line1 = value;
    }

    /**
     * Gets the value of the line2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLine2() {
        return line2;
    }

    /**
     * Sets the value of the line2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLine2(String value) {
        this.line2 = value;
    }

    /**
     * Gets the value of the line3 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLine3() {
        return line3;
    }

    /**
     * Sets the value of the line3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLine3(String value) {
        this.line3 = value;
    }

    /**
     * Gets the value of the line4 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLine4() {
        return line4;
    }

    /**
     * Sets the value of the line4 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLine4(String value) {
        this.line4 = value;
    }

    /**
     * Gets the value of the cross property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCross() {
        return cross;
    }

    /**
     * Sets the value of the cross property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCross(String value) {
        this.cross = value;
    }

    /**
     * Gets the value of the house property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHouse() {
        return house;
    }

    /**
     * Sets the value of the house property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHouse(String value) {
        this.house = value;
    }

    /**
     * Gets the value of the street property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStreet() {
        return street;
    }

    /**
     * Sets the value of the street property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStreet(String value) {
        this.street = value;
    }

    /**
     * Gets the value of the xstreet property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXstreet() {
        return xstreet;
    }

    /**
     * Sets the value of the xstreet property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXstreet(String value) {
        this.xstreet = value;
    }

    /**
     * Gets the value of the unittype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUnittype() {
        return unittype;
    }

    /**
     * Sets the value of the unittype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUnittype(String value) {
        this.unittype = value;
    }

    /**
     * Gets the value of the unit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUnit() {
        return unit;
    }

    /**
     * Sets the value of the unit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUnit(String value) {
        this.unit = value;
    }

    /**
     * Gets the value of the postal property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPostal() {
        return postal;
    }

    /**
     * Sets the value of the postal property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPostal(String value) {
        this.postal = value;
    }

    /**
     * Gets the value of the neighborhood property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNeighborhood() {
        return neighborhood;
    }

    /**
     * Sets the value of the neighborhood property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNeighborhood(String value) {
        this.neighborhood = value;
    }

    /**
     * Gets the value of the city property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCity() {
        return city;
    }

    /**
     * Sets the value of the city property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCity(String value) {
        this.city = value;
    }

    /**
     * Gets the value of the county property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCounty() {
        return county;
    }

    /**
     * Sets the value of the county property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCounty(String value) {
        this.county = value;
    }

    /**
     * Gets the value of the state property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getState() {
        return state;
    }

    /**
     * Sets the value of the state property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setState(String value) {
        this.state = value;
    }

    /**
     * Gets the value of the country property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCountry() {
        return country;
    }

    /**
     * Sets the value of the country property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCountry(String value) {
        this.country = value;
    }

    /**
     * Gets the value of the level14 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLevel14() {
        return level14;
    }

    /**
     * Sets the value of the level14 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLevel14(String value) {
        this.level14 = value;
    }

    /**
     * Gets the value of the level13 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLevel13() {
        return level13;
    }

    /**
     * Sets the value of the level13 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLevel13(String value) {
        this.level13 = value;
    }

    /**
     * Gets the value of the level12 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLevel12() {
        return level12;
    }

    /**
     * Sets the value of the level12 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLevel12(String value) {
        this.level12 = value;
    }

    /**
     * Gets the value of the level11 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLevel11() {
        return level11;
    }

    /**
     * Sets the value of the level11 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLevel11(String value) {
        this.level11 = value;
    }

    /**
     * Gets the value of the level10 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLevel10() {
        return level10;
    }

    /**
     * Sets the value of the level10 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLevel10(String value) {
        this.level10 = value;
    }

    /**
     * Gets the value of the countrycode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCountrycode() {
        return countrycode;
    }

    /**
     * Sets the value of the countrycode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCountrycode(String value) {
        this.countrycode = value;
    }

    /**
     * Gets the value of the statecode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatecode() {
        return statecode;
    }

    /**
     * Sets the value of the statecode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatecode(String value) {
        this.statecode = value;
    }

    /**
     * Gets the value of the countycode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCountycode() {
        return countycode;
    }

    /**
     * Sets the value of the countycode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCountycode(String value) {
        this.countycode = value;
    }

    /**
     * Gets the value of the level12Code property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLevel12Code() {
        return level12Code;
    }

    /**
     * Sets the value of the level12Code property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLevel12Code(String value) {
        this.level12Code = value;
    }

    /**
     * Gets the value of the level11Code property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLevel11Code() {
        return level11Code;
    }

    /**
     * Sets the value of the level11Code property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLevel11Code(String value) {
        this.level11Code = value;
    }

    /**
     * Gets the value of the level10Code property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLevel10Code() {
        return level10Code;
    }

    /**
     * Sets the value of the level10Code property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLevel10Code(String value) {
        this.level10Code = value;
    }

    /**
     * Gets the value of the areacode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAreacode() {
        return areacode;
    }

    /**
     * Sets the value of the areacode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAreacode(String value) {
        this.areacode = value;
    }

    /**
     * Gets the value of the timezone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTimezone() {
        return timezone;
    }

    /**
     * Sets the value of the timezone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTimezone(String value) {
        this.timezone = value;
    }

    /**
     * Gets the value of the uzip property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUzip() {
        return uzip;
    }

    /**
     * Sets the value of the uzip property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUzip(String value) {
        this.uzip = value;
    }

    /**
     * Gets the value of the hash property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHash() {
        return hash;
    }

    /**
     * Sets the value of the hash property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHash(String value) {
        this.hash = value;
    }

    /**
     * Gets the value of the woeid property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getWoeid() {
        return woeid;
    }

    /**
     * Sets the value of the woeid property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setWoeid(BigInteger value) {
        this.woeid = value;
    }

    /**
     * Gets the value of the woetype property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getWoetype() {
        return woetype;
    }

    /**
     * Sets the value of the woetype property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setWoetype(BigInteger value) {
        this.woetype = value;
    }

}
