package edu.iu.scipolicy.visualization.horizontalbargraph;

public final class HeaderAndFooterPositioningData {
	public static final double X_POSITION = 0.5;

	public static final double HEADER_SPACING_PERCENTAGE_DIFFERENCE = 0.0136;
	public static final double DATE_TIME_Y_PERCENTAGE = 0.9727;
	public static final double INPUT_DATA_Y_PERCENTAGE =
		DATE_TIME_Y_PERCENTAGE - HEADER_SPACING_PERCENTAGE_DIFFERENCE;
//	public static final double INPUT_DATA_Y_PERCENTAGE = 0.9591;

	public static final double DATASET_NAME_Y_PERCENTAGE = 0.9273;

	public static final double SUBHEADER_SPACING_PERCENTAGE_DIFFERENCE = 0.01275;
	public static final double LABEL_COLUMN_Y_PERCENTAGE = 0.9;
	public static final double START_DATE_COLUMN_Y_PERCENTAGE =
		LABEL_COLUMN_Y_PERCENTAGE - SUBHEADER_SPACING_PERCENTAGE_DIFFERENCE;
	public static final double END_DATE_COLUMN_Y_PERCENTAGE =
		START_DATE_COLUMN_Y_PERCENTAGE - SUBHEADER_SPACING_PERCENTAGE_DIFFERENCE;
	public static final double SIZE_BY_COLUMN_Y_PERCENTAGE =
		END_DATE_COLUMN_Y_PERCENTAGE - SUBHEADER_SPACING_PERCENTAGE_DIFFERENCE;
	public static final double DATE_FORMAT_Y_PERCENTAGE =
		SIZE_BY_COLUMN_Y_PERCENTAGE - SUBHEADER_SPACING_PERCENTAGE_DIFFERENCE;
	public static final double YEAR_LABEL_FONT_SIZE_Y_PERCENTAGE =
		DATE_FORMAT_Y_PERCENTAGE - SUBHEADER_SPACING_PERCENTAGE_DIFFERENCE;
	public static final double BAR_LABEL_FONT_SIZE_Y_PERCENTAGE =
		YEAR_LABEL_FONT_SIZE_Y_PERCENTAGE - SUBHEADER_SPACING_PERCENTAGE_DIFFERENCE;

	public static final double FOOTER_Y = 0.0318;
}