from change_password_tests import *
from display_user_profile_tests import *
from edit_profile_tests import *
from forgot_email_tests import *
from forgot_password_tests import *
from forgot_username_tests import *
from log_in_and_out_tests import *
#from multifile_upload_tests import *
from profile_dataset_tests import *
from profile_datarequests_tests import *
from profile_link_tests import *
