#!/bin/bash

x=`which gnuplot`
y=`which awk`

if [ -n "$x" ]; then
  echo "plot \"$*\";">gnuplotstart.txt
  xterm -e "gnuplot -persist gnuplotstart.txt"
else
  echo "gnuplot not found in default PATH environment variable.  "
  echo "Please include the directory containing gnuplot in the PATH variable.  "
  echo "Download and documentation is also available at http://www.gnuplot.info/."
fi
