from change_password_tests import *
from display_user_profile_tests import *
from edit_profile_tests import *
from forgot_password_tests import *
from logo_tests import *
from log_in_and_out_tests import *
from profile_datarequests_tests import *
from profile_dataset_tests import *
from profile_link_tests import *
from site_index_tests import *