//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.18 at 02:41:41 PM EDT 
//


package edu.iu.sci2.preprocessing.geocoder.coders.bing.placefinder.beans;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.microsoft.schemas.search.local.ws.rest.v1 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.microsoft.schemas.search.local.ws.rest.v1
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Response }
     * 
     */
    public Response createResponse() {
        return new Response();
    }

    /**
     * Create an instance of {@link Response.ResourceSets }
     * 
     */
    public Response.ResourceSets createResponseResourceSets() {
        return new Response.ResourceSets();
    }

    /**
     * Create an instance of {@link Response.ResourceSets.ResourceSet }
     * 
     */
    public Response.ResourceSets.ResourceSet createResponseResourceSetsResourceSet() {
        return new Response.ResourceSets.ResourceSet();
    }

    /**
     * Create an instance of {@link Response.ResourceSets.ResourceSet.Resources }
     * 
     */
    public Response.ResourceSets.ResourceSet.Resources createResponseResourceSetsResourceSetResources() {
        return new Response.ResourceSets.ResourceSet.Resources();
    }

    /**
     * Create an instance of {@link Response.ResourceSets.ResourceSet.Resources.Location }
     * 
     */
    public Response.ResourceSets.ResourceSet.Resources.Location createResponseResourceSetsResourceSetResourcesLocation() {
        return new Response.ResourceSets.ResourceSet.Resources.Location();
    }

    /**
     * Create an instance of {@link Response.ResourceSets.ResourceSet.Resources.Location.Point }
     * 
     */
    public Response.ResourceSets.ResourceSet.Resources.Location.Point createResponseResourceSetsResourceSetResourcesLocationPoint() {
        return new Response.ResourceSets.ResourceSet.Resources.Location.Point();
    }

    /**
     * Create an instance of {@link Response.ResourceSets.ResourceSet.Resources.Location.BoundingBox }
     * 
     */
    public Response.ResourceSets.ResourceSet.Resources.Location.BoundingBox createResponseResourceSetsResourceSetResourcesLocationBoundingBox() {
        return new Response.ResourceSets.ResourceSet.Resources.Location.BoundingBox();
    }

    /**
     * Create an instance of {@link Response.ResourceSets.ResourceSet.Resources.Location.Address }
     * 
     */
    public Response.ResourceSets.ResourceSet.Resources.Location.Address createResponseResourceSetsResourceSetResourcesLocationAddress() {
        return new Response.ResourceSets.ResourceSet.Resources.Location.Address();
    }

    /**
     * Create an instance of {@link Response.ResourceSets.ResourceSet.Resources.Location.GeocodePoint }
     * 
     */
    public Response.ResourceSets.ResourceSet.Resources.Location.GeocodePoint createResponseResourceSetsResourceSetResourcesLocationGeocodePoint() {
        return new Response.ResourceSets.ResourceSet.Resources.Location.GeocodePoint();
    }

}
