//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.18 at 02:41:41 PM EDT 
//


package edu.iu.sci2.preprocessing.geocoder.coders.bing.placefinder.beans;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Copyright" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="BrandLogoUri" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
 *         &lt;element name="StatusCode" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *         &lt;element name="StatusDescription" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="AuthenticationResultCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="TraceId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ResourceSets">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="ResourceSet">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="EstimatedTotal" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                             &lt;element name="Resources">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="Location" maxOccurs="unbounded" minOccurs="0">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                               &lt;sequence>
 *                                                 &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                 &lt;element name="Point">
 *                                                   &lt;complexType>
 *                                                     &lt;complexContent>
 *                                                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                                         &lt;sequence>
 *                                                           &lt;element name="Latitude" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                                                           &lt;element name="Longitude" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                                                         &lt;/sequence>
 *                                                       &lt;/restriction>
 *                                                     &lt;/complexContent>
 *                                                   &lt;/complexType>
 *                                                 &lt;/element>
 *                                                 &lt;element name="BoundingBox">
 *                                                   &lt;complexType>
 *                                                     &lt;complexContent>
 *                                                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                                         &lt;sequence>
 *                                                           &lt;element name="SouthLatitude" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                                                           &lt;element name="WestLongitude" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                                                           &lt;element name="NorthLatitude" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                                                           &lt;element name="EastLongitude" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                                                         &lt;/sequence>
 *                                                       &lt;/restriction>
 *                                                     &lt;/complexContent>
 *                                                   &lt;/complexType>
 *                                                 &lt;/element>
 *                                                 &lt;element name="EntityType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                 &lt;element name="Address">
 *                                                   &lt;complexType>
 *                                                     &lt;complexContent>
 *                                                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                                         &lt;sequence>
 *                                                           &lt;element name="AddressLine" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                                                           &lt;element name="AdminDistrict" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                                                           &lt;element name="AdminDistrict2" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                                                           &lt;element name="CountryRegion" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                           &lt;element name="FormattedAddress" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                           &lt;element name="Locality" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                                                           &lt;element name="Landmark" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                                                           &lt;element name="PostalCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                                                         &lt;/sequence>
 *                                                       &lt;/restriction>
 *                                                     &lt;/complexContent>
 *                                                   &lt;/complexType>
 *                                                 &lt;/element>
 *                                                 &lt;element name="Confidence" type="{http://www.w3.org/2001/XMLSchema}string"  maxOccurs="unbounded" minOccurs="0"/>
 *                                                 &lt;element name="MatchCode" type="{http://www.w3.org/2001/XMLSchema}string"  maxOccurs="unbounded" minOccurs="0"/>
 *                                                 &lt;element name="GeocodePoint" maxOccurs="unbounded" minOccurs="0">
 *                                                   &lt;complexType>
 *                                                     &lt;complexContent>
 *                                                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                                         &lt;sequence>
 *                                                           &lt;element name="Latitude" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                                                           &lt;element name="Longitude" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                                                           &lt;element name="CalculationMethod" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                           &lt;element name="UsageType" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *                                                         &lt;/sequence>
 *                                                       &lt;/restriction>
 *                                                     &lt;/complexContent>
 *                                                   &lt;/complexType>
 *                                                 &lt;/element>
 *                                               &lt;/sequence>
 *                                             &lt;/restriction>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "copyright",
    "brandLogoUri",
    "statusCode",
    "statusDescription",
    "authenticationResultCode",
    "traceId",
    "resourceSets"
})
@XmlRootElement(name = "Response")
public class Response {

    @XmlElement(name = "Copyright", required = true)
    protected String copyright;
    @XmlElement(name = "BrandLogoUri", required = true)
    @XmlSchemaType(name = "anyURI")
    protected String brandLogoUri;
    @XmlElement(name = "StatusCode")
    protected short statusCode;
    @XmlElement(name = "StatusDescription", required = true)
    protected String statusDescription;
    @XmlElement(name = "AuthenticationResultCode", required = true)
    protected String authenticationResultCode;
    @XmlElement(name = "TraceId", required = true)
    protected String traceId;
    @XmlElement(name = "ResourceSets", required = true)
    protected Response.ResourceSets resourceSets;

    /**
     * Gets the value of the copyright property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCopyright() {
        return copyright;
    }

    /**
     * Sets the value of the copyright property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCopyright(String value) {
        this.copyright = value;
    }

    /**
     * Gets the value of the brandLogoUri property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBrandLogoUri() {
        return brandLogoUri;
    }

    /**
     * Sets the value of the brandLogoUri property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBrandLogoUri(String value) {
        this.brandLogoUri = value;
    }

    /**
     * Gets the value of the statusCode property.
     * 
     */
    public short getStatusCode() {
        return statusCode;
    }

    /**
     * Sets the value of the statusCode property.
     * 
     */
    public void setStatusCode(short value) {
        this.statusCode = value;
    }

    /**
     * Gets the value of the statusDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatusDescription() {
        return statusDescription;
    }

    /**
     * Sets the value of the statusDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatusDescription(String value) {
        this.statusDescription = value;
    }

    /**
     * Gets the value of the authenticationResultCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAuthenticationResultCode() {
        return authenticationResultCode;
    }

    /**
     * Sets the value of the authenticationResultCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAuthenticationResultCode(String value) {
        this.authenticationResultCode = value;
    }

    /**
     * Gets the value of the traceId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTraceId() {
        return traceId;
    }

    /**
     * Sets the value of the traceId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTraceId(String value) {
        this.traceId = value;
    }

    /**
     * Gets the value of the resourceSets property.
     * 
     * @return
     *     possible object is
     *     {@link Response.ResourceSets }
     *     
     */
    public Response.ResourceSets getResourceSets() {
        return resourceSets;
    }

    /**
     * Sets the value of the resourceSets property.
     * 
     * @param value
     *     allowed object is
     *     {@link Response.ResourceSets }
     *     
     */
    public void setResourceSets(Response.ResourceSets value) {
        this.resourceSets = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="ResourceSet">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="EstimatedTotal" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *                   &lt;element name="Resources">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="Location" maxOccurs="unbounded" minOccurs="0">
     *                               &lt;complexType>
     *                                 &lt;complexContent>
     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                     &lt;sequence>
     *                                       &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                       &lt;element name="Point">
     *                                         &lt;complexType>
     *                                           &lt;complexContent>
     *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                               &lt;sequence>
     *                                                 &lt;element name="Latitude" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *                                                 &lt;element name="Longitude" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *                                               &lt;/sequence>
     *                                             &lt;/restriction>
     *                                           &lt;/complexContent>
     *                                         &lt;/complexType>
     *                                       &lt;/element>
     *                                       &lt;element name="BoundingBox">
     *                                         &lt;complexType>
     *                                           &lt;complexContent>
     *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                               &lt;sequence>
     *                                                 &lt;element name="SouthLatitude" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *                                                 &lt;element name="WestLongitude" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *                                                 &lt;element name="NorthLatitude" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *                                                 &lt;element name="EastLongitude" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *                                               &lt;/sequence>
     *                                             &lt;/restriction>
     *                                           &lt;/complexContent>
     *                                         &lt;/complexType>
     *                                       &lt;/element>
     *                                       &lt;element name="EntityType" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                       &lt;element name="Address">
     *                                         &lt;complexType>
     *                                           &lt;complexContent>
     *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                               &lt;sequence>
     *                                                 &lt;element name="AddressLine" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                                                 &lt;element name="AdminDistrict" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                                                 &lt;element name="AdminDistrict2" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                                                 &lt;element name="CountryRegion" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                                 &lt;element name="FormattedAddress" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                                 &lt;element name="Locality" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                                                 &lt;element name="Landmark" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                                                 &lt;element name="PostalCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                                               &lt;/sequence>
     *                                             &lt;/restriction>
     *                                           &lt;/complexContent>
     *                                         &lt;/complexType>
     *                                       &lt;/element>
     *                                       &lt;element name="Confidence" type="{http://www.w3.org/2001/XMLSchema}string"  maxOccurs="unbounded" minOccurs="0"/>
     *                                       &lt;element name="MatchCode" type="{http://www.w3.org/2001/XMLSchema}string"  maxOccurs="unbounded" minOccurs="0"/>
     *                                       &lt;element name="GeocodePoint" maxOccurs="unbounded" minOccurs="0">
     *                                         &lt;complexType>
     *                                           &lt;complexContent>
     *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                               &lt;sequence>
     *                                                 &lt;element name="Latitude" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *                                                 &lt;element name="Longitude" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *                                                 &lt;element name="CalculationMethod" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                                 &lt;element name="UsageType" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
     *                                               &lt;/sequence>
     *                                             &lt;/restriction>
     *                                           &lt;/complexContent>
     *                                         &lt;/complexType>
     *                                       &lt;/element>
     *                                     &lt;/sequence>
     *                                   &lt;/restriction>
     *                                 &lt;/complexContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "resourceSet"
    })
    public static class ResourceSets {

        @XmlElement(name = "ResourceSet", required = true)
        protected Response.ResourceSets.ResourceSet resourceSet;

        /**
         * Gets the value of the resourceSet property.
         * 
         * @return
         *     possible object is
         *     {@link Response.ResourceSets.ResourceSet }
         *     
         */
        public Response.ResourceSets.ResourceSet getResourceSet() {
            return resourceSet;
        }

        /**
         * Sets the value of the resourceSet property.
         * 
         * @param value
         *     allowed object is
         *     {@link Response.ResourceSets.ResourceSet }
         *     
         */
        public void setResourceSet(Response.ResourceSets.ResourceSet value) {
            this.resourceSet = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="EstimatedTotal" type="{http://www.w3.org/2001/XMLSchema}byte"/>
         *         &lt;element name="Resources">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="Location" maxOccurs="unbounded" minOccurs="0">
         *                     &lt;complexType>
         *                       &lt;complexContent>
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                           &lt;sequence>
         *                             &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                             &lt;element name="Point">
         *                               &lt;complexType>
         *                                 &lt;complexContent>
         *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                                     &lt;sequence>
         *                                       &lt;element name="Latitude" type="{http://www.w3.org/2001/XMLSchema}float"/>
         *                                       &lt;element name="Longitude" type="{http://www.w3.org/2001/XMLSchema}float"/>
         *                                     &lt;/sequence>
         *                                   &lt;/restriction>
         *                                 &lt;/complexContent>
         *                               &lt;/complexType>
         *                             &lt;/element>
         *                             &lt;element name="BoundingBox">
         *                               &lt;complexType>
         *                                 &lt;complexContent>
         *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                                     &lt;sequence>
         *                                       &lt;element name="SouthLatitude" type="{http://www.w3.org/2001/XMLSchema}float"/>
         *                                       &lt;element name="WestLongitude" type="{http://www.w3.org/2001/XMLSchema}float"/>
         *                                       &lt;element name="NorthLatitude" type="{http://www.w3.org/2001/XMLSchema}float"/>
         *                                       &lt;element name="EastLongitude" type="{http://www.w3.org/2001/XMLSchema}float"/>
         *                                     &lt;/sequence>
         *                                   &lt;/restriction>
         *                                 &lt;/complexContent>
         *                               &lt;/complexType>
         *                             &lt;/element>
         *                             &lt;element name="EntityType" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                             &lt;element name="Address">
         *                               &lt;complexType>
         *                                 &lt;complexContent>
         *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                                     &lt;sequence>
         *                                       &lt;element name="AddressLine" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *                                       &lt;element name="AdminDistrict" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *                                       &lt;element name="AdminDistrict2" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *                                       &lt;element name="CountryRegion" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                                       &lt;element name="FormattedAddress" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                                       &lt;element name="Locality" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *                                       &lt;element name="Landmark" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *                                       &lt;element name="PostalCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *                                     &lt;/sequence>
         *                                   &lt;/restriction>
         *                                 &lt;/complexContent>
         *                               &lt;/complexType>
         *                             &lt;/element>
         *                             &lt;element name="Confidence" type="{http://www.w3.org/2001/XMLSchema}string"  maxOccurs="unbounded" minOccurs="0"/>
         *                             &lt;element name="MatchCode" type="{http://www.w3.org/2001/XMLSchema}string"  maxOccurs="unbounded" minOccurs="0"/>
         *                             &lt;element name="GeocodePoint" maxOccurs="unbounded" minOccurs="0">
         *                               &lt;complexType>
         *                                 &lt;complexContent>
         *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                                     &lt;sequence>
         *                                       &lt;element name="Latitude" type="{http://www.w3.org/2001/XMLSchema}float"/>
         *                                       &lt;element name="Longitude" type="{http://www.w3.org/2001/XMLSchema}float"/>
         *                                       &lt;element name="CalculationMethod" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                                       &lt;element name="UsageType" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
         *                                     &lt;/sequence>
         *                                   &lt;/restriction>
         *                                 &lt;/complexContent>
         *                               &lt;/complexType>
         *                             &lt;/element>
         *                           &lt;/sequence>
         *                         &lt;/restriction>
         *                       &lt;/complexContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "estimatedTotal",
            "resources"
        })
        public static class ResourceSet {

            @XmlElement(name = "EstimatedTotal")
            protected byte estimatedTotal;
            @XmlElement(name = "Resources", required = true)
            protected Response.ResourceSets.ResourceSet.Resources resources;

            /**
             * Gets the value of the estimatedTotal property.
             * 
             */
            public byte getEstimatedTotal() {
                return estimatedTotal;
            }

            /**
             * Sets the value of the estimatedTotal property.
             * 
             */
            public void setEstimatedTotal(byte value) {
                this.estimatedTotal = value;
            }

            /**
             * Gets the value of the resources property.
             * 
             * @return
             *     possible object is
             *     {@link Response.ResourceSets.ResourceSet.Resources }
             *     
             */
            public Response.ResourceSets.ResourceSet.Resources getResources() {
                return resources;
            }

            /**
             * Sets the value of the resources property.
             * 
             * @param value
             *     allowed object is
             *     {@link Response.ResourceSets.ResourceSet.Resources }
             *     
             */
            public void setResources(Response.ResourceSets.ResourceSet.Resources value) {
                this.resources = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="Location" maxOccurs="unbounded" minOccurs="0">
             *           &lt;complexType>
             *             &lt;complexContent>
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                 &lt;sequence>
             *                   &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                   &lt;element name="Point">
             *                     &lt;complexType>
             *                       &lt;complexContent>
             *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                           &lt;sequence>
             *                             &lt;element name="Latitude" type="{http://www.w3.org/2001/XMLSchema}float"/>
             *                             &lt;element name="Longitude" type="{http://www.w3.org/2001/XMLSchema}float"/>
             *                           &lt;/sequence>
             *                         &lt;/restriction>
             *                       &lt;/complexContent>
             *                     &lt;/complexType>
             *                   &lt;/element>
             *                   &lt;element name="BoundingBox">
             *                     &lt;complexType>
             *                       &lt;complexContent>
             *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                           &lt;sequence>
             *                             &lt;element name="SouthLatitude" type="{http://www.w3.org/2001/XMLSchema}float"/>
             *                             &lt;element name="WestLongitude" type="{http://www.w3.org/2001/XMLSchema}float"/>
             *                             &lt;element name="NorthLatitude" type="{http://www.w3.org/2001/XMLSchema}float"/>
             *                             &lt;element name="EastLongitude" type="{http://www.w3.org/2001/XMLSchema}float"/>
             *                           &lt;/sequence>
             *                         &lt;/restriction>
             *                       &lt;/complexContent>
             *                     &lt;/complexType>
             *                   &lt;/element>
             *                   &lt;element name="EntityType" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                   &lt;element name="Address">
             *                     &lt;complexType>
             *                       &lt;complexContent>
             *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                           &lt;sequence>
             *                             &lt;element name="AddressLine" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
             *                             &lt;element name="AdminDistrict" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
             *                             &lt;element name="AdminDistrict2" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
             *                             &lt;element name="CountryRegion" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                             &lt;element name="FormattedAddress" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                             &lt;element name="Locality" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
             *                             &lt;element name="Landmark" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
             *                             &lt;element name="PostalCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
             *                           &lt;/sequence>
             *                         &lt;/restriction>
             *                       &lt;/complexContent>
             *                     &lt;/complexType>
             *                   &lt;/element>
             *                   &lt;element name="Confidence" type="{http://www.w3.org/2001/XMLSchema}string"  maxOccurs="unbounded" minOccurs="0"/>
             *                   &lt;element name="MatchCode" type="{http://www.w3.org/2001/XMLSchema}string"  maxOccurs="unbounded" minOccurs="0"/>
             *                   &lt;element name="GeocodePoint" maxOccurs="unbounded" minOccurs="0">
             *                     &lt;complexType>
             *                       &lt;complexContent>
             *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                           &lt;sequence>
             *                             &lt;element name="Latitude" type="{http://www.w3.org/2001/XMLSchema}float"/>
             *                             &lt;element name="Longitude" type="{http://www.w3.org/2001/XMLSchema}float"/>
             *                             &lt;element name="CalculationMethod" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                             &lt;element name="UsageType" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
             *                           &lt;/sequence>
             *                         &lt;/restriction>
             *                       &lt;/complexContent>
             *                     &lt;/complexType>
             *                   &lt;/element>
             *                 &lt;/sequence>
             *               &lt;/restriction>
             *             &lt;/complexContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "location"
            })
            public static class Resources {

                @XmlElement(name = "Location")
                protected List<Response.ResourceSets.ResourceSet.Resources.Location> location;

                /**
                 * Gets the value of the location property.
                 * 
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the location property.
                 * 
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getLocation().add(newItem);
                 * </pre>
                 * 
                 * 
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link Response.ResourceSets.ResourceSet.Resources.Location }
                 * 
                 * 
                 */
                public List<Response.ResourceSets.ResourceSet.Resources.Location> getLocation() {
                    if (location == null) {
                        location = new ArrayList<Response.ResourceSets.ResourceSet.Resources.Location>();
                    }
                    return this.location;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType>
                 *   &lt;complexContent>
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *       &lt;sequence>
                 *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *         &lt;element name="Point">
                 *           &lt;complexType>
                 *             &lt;complexContent>
                 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *                 &lt;sequence>
                 *                   &lt;element name="Latitude" type="{http://www.w3.org/2001/XMLSchema}float"/>
                 *                   &lt;element name="Longitude" type="{http://www.w3.org/2001/XMLSchema}float"/>
                 *                 &lt;/sequence>
                 *               &lt;/restriction>
                 *             &lt;/complexContent>
                 *           &lt;/complexType>
                 *         &lt;/element>
                 *         &lt;element name="BoundingBox">
                 *           &lt;complexType>
                 *             &lt;complexContent>
                 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *                 &lt;sequence>
                 *                   &lt;element name="SouthLatitude" type="{http://www.w3.org/2001/XMLSchema}float"/>
                 *                   &lt;element name="WestLongitude" type="{http://www.w3.org/2001/XMLSchema}float"/>
                 *                   &lt;element name="NorthLatitude" type="{http://www.w3.org/2001/XMLSchema}float"/>
                 *                   &lt;element name="EastLongitude" type="{http://www.w3.org/2001/XMLSchema}float"/>
                 *                 &lt;/sequence>
                 *               &lt;/restriction>
                 *             &lt;/complexContent>
                 *           &lt;/complexType>
                 *         &lt;/element>
                 *         &lt;element name="EntityType" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *         &lt;element name="Address">
                 *           &lt;complexType>
                 *             &lt;complexContent>
                 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *                 &lt;sequence>
                 *                   &lt;element name="AddressLine" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
                 *                   &lt;element name="AdminDistrict" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
                 *                   &lt;element name="AdminDistrict2" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
                 *                   &lt;element name="CountryRegion" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *                   &lt;element name="FormattedAddress" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *                   &lt;element name="Locality" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
                 *                   &lt;element name="Landmark" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
                 *                   &lt;element name="PostalCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
                 *                 &lt;/sequence>
                 *               &lt;/restriction>
                 *             &lt;/complexContent>
                 *           &lt;/complexType>
                 *         &lt;/element>
                 *         &lt;element name="Confidence" type="{http://www.w3.org/2001/XMLSchema}string"  maxOccurs="unbounded" minOccurs="0"/>
                 *         &lt;element name="MatchCode" type="{http://www.w3.org/2001/XMLSchema}string"  maxOccurs="unbounded" minOccurs="0"/>
                 *         &lt;element name="GeocodePoint" maxOccurs="unbounded" minOccurs="0">
                 *           &lt;complexType>
                 *             &lt;complexContent>
                 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *                 &lt;sequence>
                 *                   &lt;element name="Latitude" type="{http://www.w3.org/2001/XMLSchema}float"/>
                 *                   &lt;element name="Longitude" type="{http://www.w3.org/2001/XMLSchema}float"/>
                 *                   &lt;element name="CalculationMethod" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *                   &lt;element name="UsageType" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
                 *                 &lt;/sequence>
                 *               &lt;/restriction>
                 *             &lt;/complexContent>
                 *           &lt;/complexType>
                 *         &lt;/element>
                 *       &lt;/sequence>
                 *     &lt;/restriction>
                 *   &lt;/complexContent>
                 * &lt;/complexType>
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "name",
                    "point",
                    "boundingBox",
                    "entityType",
                    "address",
                    "confidence",
                    "matchCode",
                    "geocodePoint"
                })
                public static class Location {

                    @XmlElement(name = "Name", required = true)
                    protected String name;
                    @XmlElement(name = "Point", required = true)
                    protected Response.ResourceSets.ResourceSet.Resources.Location.Point point;
                    @XmlElement(name = "BoundingBox", required = true)
                    protected Response.ResourceSets.ResourceSet.Resources.Location.BoundingBox boundingBox;
                    @XmlElement(name = "EntityType", required = true)
                    protected String entityType;
                    @XmlElement(name = "Address", required = true)
                    protected Response.ResourceSets.ResourceSet.Resources.Location.Address address;
                    @XmlElement(name = "Confidence", required = false)
                    protected String confidence;
                    @XmlElement(name = "MatchCode", required = false)
                    protected String matchCode;
                    @XmlElement(name = "GeocodePoint")
                    protected List<Response.ResourceSets.ResourceSet.Resources.Location.GeocodePoint> geocodePoint;

                    /**
                     * Gets the value of the name property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getName() {
                        return name;
                    }

                    /**
                     * Sets the value of the name property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setName(String value) {
                        this.name = value;
                    }

                    /**
                     * Gets the value of the point property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link Response.ResourceSets.ResourceSet.Resources.Location.Point }
                     *     
                     */
                    public Response.ResourceSets.ResourceSet.Resources.Location.Point getPoint() {
                        return point;
                    }

                    /**
                     * Sets the value of the point property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link Response.ResourceSets.ResourceSet.Resources.Location.Point }
                     *     
                     */
                    public void setPoint(Response.ResourceSets.ResourceSet.Resources.Location.Point value) {
                        this.point = value;
                    }

                    /**
                     * Gets the value of the boundingBox property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link Response.ResourceSets.ResourceSet.Resources.Location.BoundingBox }
                     *     
                     */
                    public Response.ResourceSets.ResourceSet.Resources.Location.BoundingBox getBoundingBox() {
                        return boundingBox;
                    }

                    /**
                     * Sets the value of the boundingBox property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link Response.ResourceSets.ResourceSet.Resources.Location.BoundingBox }
                     *     
                     */
                    public void setBoundingBox(Response.ResourceSets.ResourceSet.Resources.Location.BoundingBox value) {
                        this.boundingBox = value;
                    }

                    /**
                     * Gets the value of the entityType property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getEntityType() {
                        return entityType;
                    }

                    /**
                     * Sets the value of the entityType property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setEntityType(String value) {
                        this.entityType = value;
                    }

                    /**
                     * Gets the value of the address property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link Response.ResourceSets.ResourceSet.Resources.Location.Address }
                     *     
                     */
                    public Response.ResourceSets.ResourceSet.Resources.Location.Address getAddress() {
                        return address;
                    }

                    /**
                     * Sets the value of the address property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link Response.ResourceSets.ResourceSet.Resources.Location.Address }
                     *     
                     */
                    public void setAddress(Response.ResourceSets.ResourceSet.Resources.Location.Address value) {
                        this.address = value;
                    }

                    /**
                     * Gets the value of the confidence property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getConfidence() {
                        return confidence;
                    }

                    /**
                     * Sets the value of the confidence property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setConfidence(String value) {
                        this.confidence = value;
                    }

                    /**
                     * Gets the value of the matchCode property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getMatchCode() {
                        return matchCode;
                    }

                    /**
                     * Sets the value of the matchCode property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setMatchCode(String value) {
                        this.matchCode = value;
                    }

                    /**
                     * Gets the value of the geocodePoint property.
                     * 
                     * <p>
                     * This accessor method returns a reference to the live list,
                     * not a snapshot. Therefore any modification you make to the
                     * returned list will be present inside the JAXB object.
                     * This is why there is not a <CODE>set</CODE> method for the geocodePoint property.
                     * 
                     * <p>
                     * For example, to add a new item, do as follows:
                     * <pre>
                     *    getGeocodePoint().add(newItem);
                     * </pre>
                     * 
                     * 
                     * <p>
                     * Objects of the following type(s) are allowed in the list
                     * {@link Response.ResourceSets.ResourceSet.Resources.Location.GeocodePoint }
                     * 
                     * 
                     */
                    public List<Response.ResourceSets.ResourceSet.Resources.Location.GeocodePoint> getGeocodePoint() {
                        if (geocodePoint == null) {
                            geocodePoint = new ArrayList<Response.ResourceSets.ResourceSet.Resources.Location.GeocodePoint>();
                        }
                        return this.geocodePoint;
                    }


                    /**
                     * <p>Java class for anonymous complex type.
                     * 
                     * <p>The following schema fragment specifies the expected content contained within this class.
                     * 
                     * <pre>
                     * &lt;complexType>
                     *   &lt;complexContent>
                     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                     *       &lt;sequence>
                     *         &lt;element name="AddressLine" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
                     *         &lt;element name="AdminDistrict" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
                     *         &lt;element name="AdminDistrict2" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
                     *         &lt;element name="CountryRegion" type="{http://www.w3.org/2001/XMLSchema}string"/>
                     *         &lt;element name="FormattedAddress" type="{http://www.w3.org/2001/XMLSchema}string"/>
                     *         &lt;element name="Locality" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
                     *         &lt;element name="Landmark" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
                     *         &lt;element name="PostalCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
                     *       &lt;/sequence>
                     *     &lt;/restriction>
                     *   &lt;/complexContent>
                     * &lt;/complexType>
                     * </pre>
                     * 
                     * 
                     */
                    @XmlAccessorType(XmlAccessType.FIELD)
                    @XmlType(name = "", propOrder = {
                        "addressLine",
                        "adminDistrict",
                        "adminDistrict2",
                        "countryRegion",
                        "formattedAddress",
                        "locality",
                        "landmark",
                        "postalCode"
                    })
                    public static class Address {

                        @XmlElement(name = "AddressLine")
                        protected String addressLine;
                        @XmlElement(name = "AdminDistrict")
                        protected String adminDistrict;
                        @XmlElement(name = "AdminDistrict2")
                        protected String adminDistrict2;
                        @XmlElement(name = "CountryRegion", required = true)
                        protected String countryRegion;
                        @XmlElement(name = "FormattedAddress", required = true)
                        protected String formattedAddress;
                        @XmlElement(name = "Locality")
                        protected String locality;
                        @XmlElement(name = "Landmark")
                        protected String landmark;
                        @XmlElement(name = "PostalCode")
                        protected String postalCode;

                        /**
                         * Gets the value of the addressLine property.
                         * 
                         * @return
                         *     possible object is
                         *     {@link String }
                         *     
                         */
                        public String getAddressLine() {
                            return addressLine;
                        }

                        /**
                         * Sets the value of the addressLine property.
                         * 
                         * @param value
                         *     allowed object is
                         *     {@link String }
                         *     
                         */
                        public void setAddressLine(String value) {
                            this.addressLine = value;
                        }

                        /**
                         * Gets the value of the adminDistrict property.
                         * 
                         * @return
                         *     possible object is
                         *     {@link String }
                         *     
                         */
                        public String getAdminDistrict() {
                            return adminDistrict;
                        }

                        /**
                         * Sets the value of the adminDistrict property.
                         * 
                         * @param value
                         *     allowed object is
                         *     {@link String }
                         *     
                         */
                        public void setAdminDistrict(String value) {
                            this.adminDistrict = value;
                        }

                        /**
                         * Gets the value of the adminDistrict2 property.
                         * 
                         * @return
                         *     possible object is
                         *     {@link String }
                         *     
                         */
                        public String getAdminDistrict2() {
                            return adminDistrict2;
                        }

                        /**
                         * Sets the value of the adminDistrict2 property.
                         * 
                         * @param value
                         *     allowed object is
                         *     {@link String }
                         *     
                         */
                        public void setAdminDistrict2(String value) {
                            this.adminDistrict2 = value;
                        }

                        /**
                         * Gets the value of the countryRegion property.
                         * 
                         * @return
                         *     possible object is
                         *     {@link String }
                         *     
                         */
                        public String getCountryRegion() {
                            return countryRegion;
                        }

                        /**
                         * Sets the value of the countryRegion property.
                         * 
                         * @param value
                         *     allowed object is
                         *     {@link String }
                         *     
                         */
                        public void setCountryRegion(String value) {
                            this.countryRegion = value;
                        }

                        /**
                         * Gets the value of the formattedAddress property.
                         * 
                         * @return
                         *     possible object is
                         *     {@link String }
                         *     
                         */
                        public String getFormattedAddress() {
                            return formattedAddress;
                        }

                        /**
                         * Sets the value of the formattedAddress property.
                         * 
                         * @param value
                         *     allowed object is
                         *     {@link String }
                         *     
                         */
                        public void setFormattedAddress(String value) {
                            this.formattedAddress = value;
                        }

                        /**
                         * Gets the value of the locality property.
                         * 
                         * @return
                         *     possible object is
                         *     {@link String }
                         *     
                         */
                        public String getLocality() {
                            return locality;
                        }

                        /**
                         * Sets the value of the locality property.
                         * 
                         * @param value
                         *     allowed object is
                         *     {@link String }
                         *     
                         */
                        public void setLocality(String value) {
                            this.locality = value;
                        }


                        /**
                         * Gets the value of the locality property.
                         * 
                         * @return
                         *     possible object is
                         *     {@link String }
                         *     
                         */
                        public String getLandmark() {
                            return landmark;
                        }

                        /**
                         * Sets the value of the locality property.
                         * 
                         * @param value
                         *     allowed object is
                         *     {@link String }
                         *     
                         */
                        public void setLandmark(String value) {
                            this.landmark = value;
                        }

                        
                        /**
                         * Gets the value of the postalCode property.
                         * 
                         * @return
                         *     possible object is
                         *     {@link String }
                         *     
                         */
                        public String getPostalCode() {
                            return postalCode;
                        }

                        /**
                         * Sets the value of the postalCode property.
                         * 
                         * @param value
                         *     allowed object is
                         *     {@link Integer }
                         *     
                         */
                        public void setPostalCode(String value) {
                            this.postalCode = value;
                        }

                    }


                    /**
                     * <p>Java class for anonymous complex type.
                     * 
                     * <p>The following schema fragment specifies the expected content contained within this class.
                     * 
                     * <pre>
                     * &lt;complexType>
                     *   &lt;complexContent>
                     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                     *       &lt;sequence>
                     *         &lt;element name="SouthLatitude" type="{http://www.w3.org/2001/XMLSchema}float"/>
                     *         &lt;element name="WestLongitude" type="{http://www.w3.org/2001/XMLSchema}float"/>
                     *         &lt;element name="NorthLatitude" type="{http://www.w3.org/2001/XMLSchema}float"/>
                     *         &lt;element name="EastLongitude" type="{http://www.w3.org/2001/XMLSchema}float"/>
                     *       &lt;/sequence>
                     *     &lt;/restriction>
                     *   &lt;/complexContent>
                     * &lt;/complexType>
                     * </pre>
                     * 
                     * 
                     */
                    @XmlAccessorType(XmlAccessType.FIELD)
                    @XmlType(name = "", propOrder = {
                        "southLatitude",
                        "westLongitude",
                        "northLatitude",
                        "eastLongitude"
                    })
                    public static class BoundingBox {

                        @XmlElement(name = "SouthLatitude")
                        protected float southLatitude;
                        @XmlElement(name = "WestLongitude")
                        protected float westLongitude;
                        @XmlElement(name = "NorthLatitude")
                        protected float northLatitude;
                        @XmlElement(name = "EastLongitude")
                        protected float eastLongitude;

                        /**
                         * Gets the value of the southLatitude property.
                         * 
                         */
                        public float getSouthLatitude() {
                            return southLatitude;
                        }

                        /**
                         * Sets the value of the southLatitude property.
                         * 
                         */
                        public void setSouthLatitude(float value) {
                            this.southLatitude = value;
                        }

                        /**
                         * Gets the value of the westLongitude property.
                         * 
                         */
                        public float getWestLongitude() {
                            return westLongitude;
                        }

                        /**
                         * Sets the value of the westLongitude property.
                         * 
                         */
                        public void setWestLongitude(float value) {
                            this.westLongitude = value;
                        }

                        /**
                         * Gets the value of the northLatitude property.
                         * 
                         */
                        public float getNorthLatitude() {
                            return northLatitude;
                        }

                        /**
                         * Sets the value of the northLatitude property.
                         * 
                         */
                        public void setNorthLatitude(float value) {
                            this.northLatitude = value;
                        }

                        /**
                         * Gets the value of the eastLongitude property.
                         * 
                         */
                        public float getEastLongitude() {
                            return eastLongitude;
                        }

                        /**
                         * Sets the value of the eastLongitude property.
                         * 
                         */
                        public void setEastLongitude(float value) {
                            this.eastLongitude = value;
                        }

                    }


                    /**
                     * <p>Java class for anonymous complex type.
                     * 
                     * <p>The following schema fragment specifies the expected content contained within this class.
                     * 
                     * <pre>
                     * &lt;complexType>
                     *   &lt;complexContent>
                     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                     *       &lt;sequence>
                     *         &lt;element name="Latitude" type="{http://www.w3.org/2001/XMLSchema}float"/>
                     *         &lt;element name="Longitude" type="{http://www.w3.org/2001/XMLSchema}float"/>
                     *         &lt;element name="CalculationMethod" type="{http://www.w3.org/2001/XMLSchema}string"/>
                     *         &lt;element name="UsageType" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
                     *       &lt;/sequence>
                     *     &lt;/restriction>
                     *   &lt;/complexContent>
                     * &lt;/complexType>
                     * </pre>
                     * 
                     * 
                     */
                    @XmlAccessorType(XmlAccessType.FIELD)
                    @XmlType(name = "", propOrder = {
                        "latitude",
                        "longitude",
                        "calculationMethod",
                        "usageType"
                    })
                    public static class GeocodePoint {

                        @XmlElement(name = "Latitude")
                        protected float latitude;
                        @XmlElement(name = "Longitude")
                        protected float longitude;
                        @XmlElement(name = "CalculationMethod", required = true)
                        protected String calculationMethod;
                        @XmlElement(name = "UsageType", required = true)
                        protected String usageType;

                        /**
                         * Gets the value of the latitude property.
                         * 
                         */
                        public float getLatitude() {
                            return latitude;
                        }

                        /**
                         * Sets the value of the latitude property.
                         * 
                         */
                        public void setLatitude(float value) {
                            this.latitude = value;
                        }

                        /**
                         * Gets the value of the longitude property.
                         * 
                         */
                        public float getLongitude() {
                            return longitude;
                        }

                        /**
                         * Sets the value of the longitude property.
                         * 
                         */
                        public void setLongitude(float value) {
                            this.longitude = value;
                        }

                        /**
                         * Gets the value of the calculationMethod property.
                         * 
                         * @return
                         *     possible object is
                         *     {@link String }
                         *     
                         */
                        public String getCalculationMethod() {
                            return calculationMethod;
                        }

                        /**
                         * Sets the value of the calculationMethod property.
                         * 
                         * @param value
                         *     allowed object is
                         *     {@link String }
                         *     
                         */
                        public void setCalculationMethod(String value) {
                            this.calculationMethod = value;
                        }

                        /**
                         * Gets the value of the usageType property.
                         * 
                         * @return
                         *     possible object is
                         *     {@link String }
                         *     
                         */
                        public String getUsageType() {
                            return usageType;
                        }

                        /**
                         * Sets the value of the usageType property.
                         * 
                         * @param value
                         *     allowed object is
                         *     {@link String }
                         *     
                         */
                        public void setUsageType(String value) {
                            this.usageType = value;
                        }

                    }


                    /**
                     * <p>Java class for anonymous complex type.
                     * 
                     * <p>The following schema fragment specifies the expected content contained within this class.
                     * 
                     * <pre>
                     * &lt;complexType>
                     *   &lt;complexContent>
                     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                     *       &lt;sequence>
                     *         &lt;element name="Latitude" type="{http://www.w3.org/2001/XMLSchema}float"/>
                     *         &lt;element name="Longitude" type="{http://www.w3.org/2001/XMLSchema}float"/>
                     *       &lt;/sequence>
                     *     &lt;/restriction>
                     *   &lt;/complexContent>
                     * &lt;/complexType>
                     * </pre>
                     * 
                     * 
                     */
                    @XmlAccessorType(XmlAccessType.FIELD)
                    @XmlType(name = "", propOrder = {
                        "latitude",
                        "longitude"
                    })
                    public static class Point {

                        @XmlElement(name = "Latitude")
                        protected float latitude;
                        @XmlElement(name = "Longitude")
                        protected float longitude;

                        /**
                         * Gets the value of the latitude property.
                         * 
                         */
                        public float getLatitude() {
                            return latitude;
                        }

                        /**
                         * Sets the value of the latitude property.
                         * 
                         */
                        public void setLatitude(float value) {
                            this.latitude = value;
                        }

                        /**
                         * Gets the value of the longitude property.
                         * 
                         */
                        public float getLongitude() {
                            return longitude;
                        }

                        /**
                         * Sets the value of the longitude property.
                         * 
                         */
                        public void setLongitude(float value) {
                            this.longitude = value;
                        }

                    }

                }

            }

        }

    }

}
