package edu.iu.nwb.analysis.isidupremover;

public class ISITag {
	public static final String ABSTRACT = "AB";
	public static final String ARTICLE_NUMBER_OF_NEW_APS_JOURNALS = "AR";
	public static final String AUTHORS = "AU";
	public static final String BEGINNING_PAGE = "BP";
	public static final String RESEARCH_ADDRESSES = "C1";
	public static final String CITED_REFERENCES = "CR";
	public static final String ORIGINAL_KEYWORDS = "DE";
	public static final String DOI = "DI";
	public static final String DOCUMENT_TYPE = "DT";
	public static final String ENDING_PAGE = "EP";
	public static final String END_OF_A_RECORD = "ER";
	public static final String ISI_DOCUMENT_DELIVERY_NUMBER = "GA";
	public static final String NEW_KEYWORDS_GIVEN_BY_ISI = "ID";
	public static final String ISSUE = "IS";
	public static final String TWENTY_NINE_CHARACTER_JOURNAL_TITLE_ABBREVIATION = "J9";
	public static final String ISO_JOURNAL_TITLE_ABBREVIATION = "JI";
	public static final String LANGUAGE = "LA";
	public static final String CITED_REFERENCE_COUNT = "NR";
	public static final String PUBLICATION_DATE = "PD";
	public static final String THE_NUMBER_OF_PAGES = "PG";
	public static final String PUBLISHER_CITY = "PI";
	public static final String PART_NUMBER = "PN";
	public static final String PUBLICATION_TYPE = "PT";
	public static final String PUBLISHER = "PU";
	public static final String PUBLICATION_YEAR = "PY";
	public static final String REPRINT_ADDRESS = "RP";
	public static final String BOOK_SERIES_TITLE = "SE";
	public static final String SPECIAL_ISSUE = "SI";
	public static final String ISSN = "SN";
	public static final String FULL_JOURNAL_TITLE = "SO";
	public static final String SUPPLEMENT = "SU";
	public static final String TIMES_CITED = "TC";
	public static final String TITLE = "TI";
	public static final String UNIQUE_ID = "UT";
	public static final String VOLUME = "VL";
	public static final String PUBLISHER_WEB_ADDRESS = "WP";
}
