#!/bin/sh

# edit the line below
export GUESS_HOME=`pwd`

echo ""
echo "Starting GUESS..."
echo ""
echo "The initial layout for your visualization is random.  For a clearer visualization, please run a layout from the Layout menu.  (We recommend GEM.)"
echo ""
echo "GUESS log file for this session can be found in ${GUESS_HOME}/guesslog.txt"

export GUESS_LIB="$GUESS_HOME/lib"

export GCLASSPATH="$GUESS_LIB/guess.jar:$GUESS_LIB/piccolo.jar:$GUESS_LIB/piccolox.jar:$GUESS_LIB/jung.jar:$GUESS_LIB/commons-collections.jar:$GUESS_LIB/hsqldb.jar:$GUESS_LIB/freehep-all.jar:$GUESS_LIB/colt.jar:$GUESS_LIB/prefuse.jar:$GUESS_LIB/TGGraphLayout.jar:$GUESS_LIB/looks.jar:$GUESS_LIB/mascoptLib.jar:$GUESS_LIB/jfreechart.jar:$GUESS_LIB/jide-components.jar:$GUESS_LIB/jide-common.jar:$GUESS_LIB/forms.jar:$GUESS_LIB/jcommon.jar"

# echo $GCLASSPATH

java -Xms256m -Xmx1500m -DgHome=$GUESS_HOME -classpath $GCLASSPATH "-Dpython.home=$GUESS_HOME/src" com.hp.hpl.guess.Guess $@ &> guesslog.txt

PID=$!
clean(){ kill $PID  
}
trap clean INT TERM
wait $PID

echo $?
